### ISSUE TITLE
I have failed to build docker-compose on Mac

### ISSUE THREAD

**Issue by franklili3** [blockchain-certificates/cert-viewer#33]
I use Mac Os. After I installed Docker and clone, when I build docker-compose use Administrator, I failed. The error is "OSError: [Errno 5] Input/output error: '/tmp/pip_build_root/Flask/flask/testsuite/test_apps/moduleapp/apps'

Storing debug log for failure in /root/.pip/pip.log
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install /cert-viewer' returned a non-zero code: 2" 
How can I do?

**Comment by kimdhamilton** [comment]
@downie does this sound like the docker issues you ran into when recently installing? I remember we noticed some different behavior in the latest docker version, and I'm not sure if we ever got past that.

thanks for reporting this @franklili3 -- I'll take a look

**Comment by downie** [comment]
No, I got a more cryptic message, which I think is due to running on OS X Sierra beta. I'm still having issues with docker.

**Comment by kimdhamilton** [comment]
I updated the docker-compose file to use v2 file format. I recommend uninstalling whichever Docker version you had previously and installing [Docker for Mac](https://docs.docker.com/engine/installation/mac/), since this is a more seamless experience. 

I followed those steps and it works perfectly for me on mac. I updated the README.md accordingly. 

Note that we don't want to get in the business of debugging Docker installation issues, so I'm trying to keep our install notes general, and point people to Docker help when it's actually Docker installation issues. If you guys have any guidance on how best to indicate that in the docs (other than the wording I picked), please let me know. There are many varieties of versions and os combinations, and we could easily spend most of our time supporting Docker. :)

**Comment by franklili3** [comment]
My OS is OS X EI Capitan 10.11.6. I have uninstalled the Docker, and reinstall it. I have deleted the cert-viewer file folder, and clone it again, and do the left actions. I am successful to view the web page. Thanks.
